name: bearscouts
description: FRC Team 930's Scouting App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  path_provider: ^2.0.9
  crypto: ^3.0.1
  file_picker: ^4.5.1
  qr_flutter: ^4.0.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
