# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "11.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.2"

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze
